### ISSUE TITLE
Can't achieve performance from your examples

### ISSUE THREAD

**Issue by deiucanta** [orgsync/react-list#28]
Hello, 

I'm trying to mimic your last example with the two-dimensional grid. Here is my code

```jsx
var React = require('react'),
    ReactList = require('react-list'),
    mountNode = document.getElementById("app"),
    size = 10000;

var Grid = React.createClass({
  render: function() {
    return (
      <div className='grid'>
        <ReactList
          itemRenderer={this.renderRow}
          length={size}
          type='uniform'
        />
      </div>
    );
  },
  renderRow: function(row, key) {
    var renderCell = this.renderCell;
    return (
      <ReactList
        key={key}
        itemRenderer={function(column, key) {
          return renderCell(column + (size * row), key);
        }}
        length={size}
        type='uniform'
        axis='x'
      />
    );
  },
  renderCell: function(index, key) {
    return (
      <div key={key} className='cell'>
        {index}
      </div>
    );
  },
});

React.render(<Grid />, mountNode);
```

```css
body {
  -webkit-user-select: none;
}

.grid {
  overflow: auto;
  height: 600px;
  -webkit-overflow-scrolling: touch;
}

.cell {
  display: inline-block;
  width: 100px;
  height: 100px;
  line-height: 100px;
  text-align: center;
  border: 1px solid gray;
  border-bottom: none;
  border-right: none;
}
```

I'm not sure what I'm doing wrong but I see a lack of performance. I tried to tweak the threshold and pageSize but it got even worse.

Also, I tried to create a jsfiddle link with the last version but I can't get a reference to ReactList. However, it works version 0.4.2.
